### ISSUE TITLE
Gitlab repository does not exist - cannot clone

### ISSUE THREAD

**Issue by LeonardooAlves** [GaloisInc/BESSPIN-GFE-2019#2]
Hi. I am trying to replicated the implementation of the GFE with the P2 processor. But I cannot clone the GitLab `git@gitlab-ext.galois.com:ssith/gfe.git ` project. The ReadMe also mention folders that are not part of this BESSPIN-GFE-2019 folder in GitHub. How can I have access to the GitLab folder?

Thank you.

**Comment by kiniry** [comment]
The GitLab GFE project has been migrated to GitHub and finally open sourced recently as https://github.com/GaloisInc/BESSPIN-GFE.  It took quite some time to jump through all of the government's hoops to get this complete.  Apologies for the delay.
